# Site settings
title: Pym.me
logo: site-logo.svg
description: I used to be a developer like you, then I took an arrow in the knee.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://pym.me # the base hostname & protocol for your site
feed_url: http://feed.pym.me
permalink: /posts/:title
navigation:
  - slug: /monkeys/see-no-evil-monkey
    label: 🙈
  - slug: /monkeys/speak-no-evil-monkey
    label: 🙊
  - slug: /monkeys/hear-no-evil-monkey
    label: 🙉

# Build settings
exclude: [public, bower_components, bower.json, CNAME]
markdown: kramdown

# Plugins
gems: [jekyll-paginate]
paginate: 5

# Services
analytics: UA-6852835-7
facebook_l10n: fr_FR
twitter: Pym
disqus: pym-me
